version: "3.0"
services:
  homepage:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./.env:/backend/build/.env:ro
      - ./static:/frontend/build/static:ro
      - ~:/files:ro
    depends_on:
      - database
  database:
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
volumes:
  database:
    external: true